---
# tasks file for Solana RPC
- name: var check
  include_tasks: var_check.yaml

- name: create user
  include_tasks: user.yaml

- name: install dependencies
  include_tasks: deps.yaml

- name: folders
  include_tasks: dirs.yaml

- name: swap
  include_tasks: swap.yaml

- name: setup disks
  include_tasks: disks.yaml
  when: setup_disks|default(false)|bool == true

- name: logrotate
  include_tasks: rotate.yaml

- name: file setup
  include_tasks: file_setup.yaml

- name: tune host
  include_tasks: tuner.yaml


